### ISSUE TITLE
Allow the user to display the elapsed time

### ISSUE THREAD

**Issue by Lgneous** [Mstrodl/elcord#11]
I would like the ability to display the elapsed time as an option, the same way you can set `elcord-display-buffer-details` to `t` or `nil`.
The result would look like this:
![Screenshot from 2019-05-31 19-15-35](https://user-images.githubusercontent.com/32403402/58722729-7de75d00-83d8-11e9-90e7-6af367fcf33d.png)
I already have a working version, I could make a PR if you accept the feature request.

**Comment by Zulu-Inuoe** [comment]
@Lgneous I was just about to write it, but if you've already got it working then please by all means send in the PR.

It's funny you bring this up today because just yesterday I was thinking of adding it.
Thanks!

**Comment by Zulu-Inuoe** [comment]
Oh BTW can you go ahead and set it as enabled by default? That seems to be what other Editors have it set to, so it'd make sense

**Comment by Zulu-Inuoe** [comment]
Closed via 0f311c2bcfd65721fe8c0ebec9da344f217d4061
