### ISSUE TITLE
Add nim-mode icon

### ISSUE THREAD

**Issue by berquist** [Mstrodl/elcord#14]
Can you add the Nim icon for `nim-mode`? Thank you!

<img src="https://raw.githubusercontent.com/nim-lang/assets/master/Art/logo-crown.png" width="500" />

**Comment by Mstrodl** [comment]
@berquist You can [create your own application](https://discordapp.com/developers/applications/me) and add your own images! (There is a limit of 50 icons per application, so it's best to choose sparingly)
