### ISSUE TITLE
Change the old Emacs icon to the new one

### ISSUE THREAD

**Issue by Tiv0w** [Mstrodl/elcord#16]
Would be nice to have elcord use the new Emacs icon.
https://commons.wikimedia.org/wiki/File:EmacsIcon.svg

**Comment by Mstrodl** [comment]
Unfortunately I don't own the new client, @Zulu-Inuoe created it.

**Comment by Tiv0w** [comment]
Could you assign @Zulu-Inuoe to the issue please ?

**Comment by Zulu-Inuoe** [comment]
@Tiv0w Hey, sorry for the delay.

Thanks for opening this. I'd meant to update the icon a while back but forgot.
I've just updated it. If you don't see it right away you might have to restart Discord/wait for it to re-cache.

Thanks!

**Comment by Tiv0w** [comment]
Thanks ! Much better now :smile:
