### ISSUE TITLE
Does not work with Rust

### ISSUE THREAD

**Issue by MagicRB** [Mstrodl/elcord#23]
I already checked if rust-mode is being detected and it is. By doesn't work i mean that it did show up in discord when i was editing a lisp file, (.emacs), but it does not update when I switch to a Rust file

**Comment by Zulu-Inuoe** [comment]
What major mode are you using for editing Rust files?

**Comment by MagicRB** [comment]
how do i check?

**Comment by Zulu-Inuoe** [comment]
When in a rust file. you can do
`M-: RET major-mode RET`
to check the value of `major-mode` (that is, Alt+Shift+Colon, then type `major-mode`)

**Comment by MagicRB** [comment]
it says rust-mode

**Comment by MagicRB** [comment]
now it picked it up

**Comment by Zulu-Inuoe** [comment]
Oh, is it working?
elcord updates every so often (15 seconds until recently and now it's customizable)
so it may not pick it up right away. This is following the update guidelines here: https://discordapp.com/developers/docs/rich-presence/how-to
which says to update every 15 seconds

**Comment by MagicRB** [comment]
it started updating just now, I have installed it a few days prior, it never worked, so I looked into it just now and it started working. ¯\_(ツ)_/¯
Thanks for the help, if something breaks, I'll let you know. Oh and this package is great when compared to the other one.

**Comment by Zulu-Inuoe** [comment]
Great!
Let us know if run into any trouble.
