### ISSUE TITLE
Support Discord API

### ISSUE THREAD

**Issue by ericdallo** [Mstrodl/elcord#32]
I don't use Discord desktop client since I use it with [Franz](https://meetfranz.com/), so I use the web page.
It would be nice to have elcord request discord API if it supports it

**Comment by chaoky** [comment]
discord doesn't support that

**Comment by Zulu-Inuoe** [comment]
Yes, unfortunately I don't think this is possible right now

**Comment by ericdallo** [comment]
Ok, Its so common software have this that I though Discord have that, thanks

**Comment by Mstrodl** [comment]
@ericdallo Presence would necessitate us connecting to the Discord websocket as a user account which is very much against the TOS. Sorry.
