### ISSUE TITLE
Idle support

### ISSUE THREAD

**Issue by chaoky** [Mstrodl/elcord#33]
It would be nice to have elcord stop or change text when the user is idle.
it could be configured via an option: `(setq elcord-idletimer 360)`.

**Comment by Mstrodl** [comment]
Going to close this since your PR was merged... :P

**Comment by chaoky** [comment]
not quite e.e

**Comment by fmichaut-dev** [comment]
> Going to close this since your PR was merged... :P

Hm no it is not @Mstrodl 
https://github.com/Mstrodl/elcord/pull/34

**Comment by Lord-Valen** [comment]
This should be closed as #66 was merged.
