### ISSUE TITLE
Godot File Support

### ISSUE THREAD

**Issue by LennyPhoenix** [Mstrodl/elcord#38]
Could we get support for GDScript, TSCN and TRES files? I'd be willing to make the PR.

**Comment by LennyPhoenix** [comment]
Icon Suggestion:
![Godot Logo](https://user-images.githubusercontent.com/57148878/112122731-7b12b900-8bb8-11eb-83e7-a7d2532a92d5.png)

**Comment by Zulu-Inuoe** [comment]
@LennyPhoenix I went ahead and uploaded an asset `godot-mode_icon` with the Godot icon. If you can figure out the modes to use it for, by all means send a PR.

Thanks!

**Comment by Zulu-Inuoe** [comment]
Ah I see you called it `gdscript-mode_icon`. I'll go ahead and rename it on my side & merge the PR. Thanks

**Comment by LennyPhoenix** [comment]
Alright, sorry for the confusion with the filename :P
Cheers 👍
