### ISSUE TITLE
Add support for typescript-mode

### ISSUE THREAD

**Issue by wizardlink** [Mstrodl/elcord#44]
Since there is already a `js-mode` support, I don't see why not support [`typescript-mode`](https://github.com/emacs-typescript/typescript.el) too.

Image example:

<img src="https://coryrylan.com/assets/images/posts/types/typescript.png" height="150px" />

**Comment by Zulu-Inuoe** [comment]
Thanks. I've added the icon as `typescript-mode_icon`

@wizardlink Could you point me in the direction of some modes this should be active in? need this for `elcord-mode-icon-alist`.
And while you're there, could you check what the mode's name is? If it's something confusing/misleading we'd want something special for `elcord-mode-text-alist` 

I'd really appreciate it! Busy week this one.

**Comment by wizardlink** [comment]
https://github.com/emacs-typescript/typescript.el

It is called `typescript-mode`. This is the only name/implementation I know of for this major mode.

**Comment by Zulu-Inuoe** [comment]
Added in 4a53075
Thanks @wizardlink
