### ISSUE TITLE
Elcord not working with Flatpak installation of Discord

### ISSUE THREAD

**Issue by Pistrie** [Mstrodl/elcord#47]
I recently uninstalled my native discord in favor of the flatpak version, but elcord is unable to connect now.

**Comment by Mstrodl** [comment]
@Pistrie To my knowledge, it is impossible to support Flatpak because it isolates the socket we need to connect to. See #8

**Comment by sylvester-roos** [comment]
Found this issue again. It's possible by following this page: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)
