### ISSUE TITLE
Terraform icon not showing up

### ISSUE THREAD

**Issue by sebastianmarines** [Mstrodl/elcord#58]
Hi, I created #57 to add support for Terraform, the PR was merged but the icon doesn't show up in Discord.
![image](https://user-images.githubusercontent.com/18373185/146577169-8bbd1c8b-4aa2-441b-9dba-68c74b36c5e2.png)

I checked the **Publish icons** workflow that ran when my PR was merged and it seems like it failed to publish the new icon.
![image](https://user-images.githubusercontent.com/18373185/146576908-180819df-a609-4c65-bec9-c7ace7039e89.png)

I'm fairly new to Emacs Lisp so I don't know if I need to add something else to my PR or if the maintainers need to try to publish the icon.

Thanks in advance.

**Comment by Zulu-Inuoe** [comment]
Hi @sebastianmarines funny you open this up just now. I contacted @Mstrodl  about this exact thing and they've corrected the issue & re-run the workflow

The icon now shows in the dev portal and should be getting pulled into elcord now
