### ISSUE TITLE
Add Shell Icon

### ISSUE THREAD

**Issue by ura43** [Mstrodl/elcord#59]
I write a ton of shell scripts, a shell icon would be cool

**Comment by ura43** [comment]
Just wanted to note that I no longer use elcord.
Prioritize other issues first if you ever come back

**Comment by ura43** [comment]
dead project

**Comment by ura43** [comment]
:upside_down_face:

**Comment by Mstrodl** [comment]
> dead project

This is involves a one-line change and the addition of an image. If this is something you want to see, you're free to submit a PR and it'll probably get merged. Otherwise, it's unlikely to happen because I don't have the time in my life to devote to sourcing an image for every major mode requested
