### ISSUE TITLE
Add icons — Emacs CN, Cute Doom, Lua, Fortran, GNU Octave, Docker

### ISSUE THREAD

**Issue by Feyorsh** [Mstrodl/elcord#79]
Seeing as the icon cap on Discord applications has been increased to 300, here are a few more icons. Also, the Terraform icon has been updated to meet Discord's 512x512 minimum resolution.

Emacs Dragon (see [Emacs China](https://emacs-china.org/))
![emacs_dragon_icon](https://user-images.githubusercontent.com/44840644/231627981-c31595e7-732f-494e-982b-069592dfb134.png)
Doom Cute (also referenced in #49)
![doom_cute_icon](https://user-images.githubusercontent.com/44840644/231628110-2b241da6-bce3-4147-be09-a9c46417ecef.png)
Lua
![lua-mode_icon](https://user-images.githubusercontent.com/44840644/231628379-584ba6b5-e42a-4420-ba39-5279a4c0d9e9.png)
Fortran
![fortran-mode_icon](https://user-images.githubusercontent.com/44840644/231628169-63cb270c-16ad-4655-98d4-85167e975d91.png)
GNU Octave
![octave-mode_icon](https://user-images.githubusercontent.com/44840644/231628203-bd2fe845-bd1d-40f8-95da-df1ea53957d6.png)
Docker(file)
![dockerfile-mode_icon](https://user-images.githubusercontent.com/44840644/231632083-fdd0588d-313b-4386-9040-a418f94eddc2.png)

**Comment by BeBel42** [comment]
I have another icon I'd propose to add - if I may.
It is the beautyline emacs icon: (I'll provide an svg file)

![emacs-beautyline-icon](https://github.com/Mstrodl/elcord/assets/64377698/61c3e0c7-ad2a-48d8-888a-b4ffdaa4bba9)
