### ISSUE TITLE
Not connection, elcord: attempting reconnect..

### ISSUE THREAD

**Issue by kkhan01** [Mstrodl/elcord#8]
On ubuntu 16.04, installed discord via snap store, and elcord refuses to connect. Tried config with `use-package` and `require` as shown in the readme. Elcord was definitely installed, but it just keeps trying to reconnect.

**Comment by Mstrodl** [comment]
@kkhan01 I'm thinking this might simply be a limitation of ubuntu snaps. Try installing it using [the tarball](https://discordapp.com/api/download?platform=linux&format=tar.gz) and see if the problem persists

**Comment by kkhan01** [comment]
Awesome. This worked, guess you need the full desktop app. Hopefully this helps someone else with their vanity goals.
