### ISSUE TITLE
Which additional setup is needed for elcord to support arRPC?

### ISSUE THREAD

**Issue by Seme4eg** [Mstrodl/elcord#90]
Switched from webcord to armcord, which supports rich presence via [arRPC](https://arrpc.openasar.dev/), but it doesn't work out of the box. Should it? Is additional setup needed? Or it isn't supported at all for now?

2 lines present in *Messages* buffer:
```
elcord: connecting...
elcord: connected. starting updates
```
But i don't see any rich presence in armcord (ofc i do have arrpc enabled in armcord's settings.

**Comment by Mstrodl** [comment]
Hi,
Sounds like an issue with the project you're using. Please file an issue with them. Sorry!
