### ISSUE TITLE
file:// links don't work in Elcord Icon Base

### ISSUE THREAD

**Issue by ObjectsCountries** [Mstrodl/elcord#96]
(This is Emacs 29.4.) Using a file:// link in the Elcord Icon Base field does not work. Additionally, it seems to cause the icon of the Rich Presence to fall back to the pen icon, regardless of what Elcord Editor Icon is set to. The fallback icon displays no text when hovered, and there is no miniature icon in its bottom right, despite the setting being on. I've also tried the same link without file://, but the same issues occur. This only occurs when I set the Elcord Icon Base setting to something other than the repo; if it's the repo, everything works properly.

![image](https://github.com/user-attachments/assets/36b4efaf-9d37-4bcb-9d98-34b320789ca6)

![image](https://github.com/user-attachments/assets/31f83523-b5df-4298-ac3c-018f0ada395c)

**Comment by Mstrodl** [comment]
`file://` will not work. This is a discord limitation.
